using System;
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyCompany("Mariana.AVM2")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0")]
[assembly: AssemblyVersion("1.0.0.0")]

[assembly: InternalsVisibleTo("Mariana.AVM2.Tests")]

// Generated by the MSBuild WriteCodeFragment class.

